# Generated by Django 5.0 on 2024-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nftapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ranking_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
