# Generated by Django 5.0 on 2024-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nftapp', '0002_applicant_ranking_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(upload_to='../cvs/'),
        ),
    ]
