# Generated by Django 5.0 on 2024-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nftapp', '0003_alter_applicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
