# Generated by Django 5.0 on 2024-01-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Nftapp", "0004_alter_applicant_cv"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("professional_summary", models.TextField()),
                ("education", models.TextField()),
                ("work_experience", models.TextField()),
                ("skills", models.TextField()),
                ("certifications_training", models.TextField()),
                ("projects", models.TextField(blank=True, null=True)),
                ("achievements_awards", models.TextField(blank=True, null=True)),
                ("publications_presentations", models.TextField(blank=True, null=True)),
                ("languages", models.TextField(blank=True, null=True)),
                ("professional_memberships", models.TextField(blank=True, null=True)),
                ("volunteer_experience", models.TextField(blank=True, null=True)),
                ("hobbies_interests", models.TextField(blank=True, null=True)),
                ("references", models.TextField()),
            ],
        ),
    ]
