# Generated by Django 5.0 on 2024-01-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Nftapp", "0006_remove_resume_achievements_awards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="cv",
            field=models.FileField(default=1, upload_to="cvs/"),
            preserve_default=False,
        ),
    ]
